// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnEJa5mDEER5U_PO2bLgrdesPiPr4r3yU',
    appId: '1:702142515222:web:49f84dd24f691b849c0d37',
    messagingSenderId: '702142515222',
    projectId: 'ehliyet-sinav-uygulamasi',
    authDomain: 'ehliyet-sinav-uygulamasi.firebaseapp.com',
    databaseURL: 'https://ehliyet-sinav-uygulamasi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ehliyet-sinav-uygulamasi.firebasestorage.app',
    measurementId: 'G-B4ML9J2610',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXlpOqNd9qM5lq97yjmT7QRWupVbuXAKc',
    appId: '1:702142515222:android:b3f76b459d7a197e9c0d37',
    messagingSenderId: '702142515222',
    projectId: 'ehliyet-sinav-uygulamasi',
    databaseURL: 'https://ehliyet-sinav-uygulamasi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ehliyet-sinav-uygulamasi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDZyYZSmUjJNWXMK1tsIy3pUxjJsJUzT8',
    appId: '1:702142515222:ios:49c90e7ba3f2611f9c0d37',
    messagingSenderId: '702142515222',
    projectId: 'ehliyet-sinav-uygulamasi',
    databaseURL: 'https://ehliyet-sinav-uygulamasi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ehliyet-sinav-uygulamasi.firebasestorage.app',
    iosBundleId: 'com.example.ehliyetSinavUyg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDZyYZSmUjJNWXMK1tsIy3pUxjJsJUzT8',
    appId: '1:702142515222:ios:49c90e7ba3f2611f9c0d37',
    messagingSenderId: '702142515222',
    projectId: 'ehliyet-sinav-uygulamasi',
    databaseURL: 'https://ehliyet-sinav-uygulamasi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ehliyet-sinav-uygulamasi.firebasestorage.app',
    iosBundleId: 'com.example.ehliyetSinavUyg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnEJa5mDEER5U_PO2bLgrdesPiPr4r3yU',
    appId: '1:702142515222:web:ea9cb97f80766d139c0d37',
    messagingSenderId: '702142515222',
    projectId: 'ehliyet-sinav-uygulamasi',
    authDomain: 'ehliyet-sinav-uygulamasi.firebaseapp.com',
    databaseURL: 'https://ehliyet-sinav-uygulamasi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ehliyet-sinav-uygulamasi.firebasestorage.app',
    measurementId: 'G-0Q8LEB8NLX',
  );
}
